name: aarch64

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: setup rust stable
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        rustup target add aarch64-unknown-linux-gnu
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: build
      run: |
        cargo build --release --target aarch64-unknown-linux-gnu

    - name: upload bundle
      uses: actions/upload-artifact@v4
      with:
        name: aarch64
        path: target/aarch64-unknown-linux-gnu/release/psv
