name: macOS

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: unit tests
      run: |
        cargo test --all --release

    - name: upload bundle
      uses: actions/upload-artifact@v4
      with:
        name: macos
        path: target/release/psv