name: armv7

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4

    - name: setup rust stable
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        rustup target add armv7-unknown-linux-gnueabi
        sudo apt-get install -y gcc-arm-linux-gnueabi

    - name: unit tests
      run: |
        cargo build --release --target armv7-unknown-linux-gnueabi

    - name: upload bundle
      uses: actions/upload-artifact@v4
      with:
        name: armv7
        path: target/armv7-unknown-linux-gnueabi/release/psv
